<div class="field">
    <label class="label" for="linkedin_profile">
        <span><?= __('LinkedIn Profile ');?></span>
    </label>
    <div class="control">
        <input type="url"  name="linkedin_profile" id="linkedin_profile" value=""
               title="<?= __('LinkedIn Profile'); ?>" class="input-text" minlength="15" maxlength="250"
               data-validate="{'validate-url':true}">
    </div>
</div>


